services:
  web:
    build:
      context: ./docker/backend
      dockerfile: web.Dockerfile
    restart: always
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./docker/backend/nginx/conf:/etc/nginx/conf.d
      - ./docker/backend/www:/var/www
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - php-main
    ports:
      - 127.0.0.1:80:80
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 10s
      retries: 3

  php-main:
    build:
      context: ./docker/backend
      dockerfile: php-main.Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/backend/www:/var/www
    networks:
      - db
      - backend

  mysql:
    image: "mysql:${MYSQL_VERSION}"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  backend:
  db:

volumes:
  mysql:
  letsencrypt:
