services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    # Restart the container always for continuous availability.
    # restart: always
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/var/www
      # Mount cache directories into Nginx container to improve performance.
      # - ./nginx/cache:/etc/nginx/cache
      # - ./nginx/cache:/var/run/nginx/cache
      # Persist Let's Encrypt certificates for SSL.
      # - ./letsencrypt/etc:/etc/letsencrypt
    depends_on:
      - backend
    ports:
      - 80:80
      # - 443:443
    networks:
      common:
        ipv4_address: 172.18.0.2

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Restart the container always for continuous availability.
    # restart: always
    volumes:
      - ./www:/var/www
    networks:
      common:
        ipv4_address: 172.18.0.3

  sftpgo:
    image: drakkan/sftpgo:latest
    ports:
      - 8080:8080
      - 2022:2022
      - 10080:10080
    volumes:
      - ./sftpgo/data:/srv/sftpgo
      - ./sftpgo/home:/var/lib/sftpgo
      # Mount SSL certificates for SFTPGo to secure SFTP connections.
      # - ./sftpgo/certs:/var/lib/sftpgo/certs
      - ./sftpgo/logs:/var/log/sftpgo
      - ./www:/var/www
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
      SFTPGO_LOG_FILE_PATH: /var/log/sftpgo/sftpgo.log
    networks:
      common:
        ipv4_address: 172.18.0.4

  db:
    image: mysql:8.0
    # Restart the container always for continuous availability.
    # restart: always
    volumes:
      # Persist MySQL data directory on the host machine.
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: "user"
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    ports:
      - 3306:3306
    networks:
      common:
        ipv4_address: 172.18.0.5

  phpmyadmin:
    image: phpmyadmin
    # Restart the container always for continuous availability.
    # restart: always
    ports:
      - 8083:80
    networks:
      common:
        ipv4_address: 172.18.0.6
    environment:
      PMA_ARBITRARY: 1

  certbot:
    image: certbot/certbot:latest
    volumes:
      # Persist Let's Encrypt certificates for SSL.
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/var:/var/lib/letsencrypt
      - ./www/certbot:/var/www/certbot
    networks:
      common:
        ipv4_address: 172.18.0.7

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

networks:
  common:
    ipam:
      config:
        - subnet: 172.18.0.0/24
