services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/var/www
      # - ./nginx/cache:/etc/nginx/cache
      # - ./nginx/cache:/var/run/nginx/cache
      # - ./letsencrypt/etc:/etc/letsencrypt
    depends_on:
      - php-main
    ports:
      - 80:80
      # - 443:443
    networks:
      common:
        ipv4_address: 172.18.0.2

  php-main:
    build:
      context: .
      dockerfile: Dockerfile.php-main
    restart: always
    volumes:
      - ./www:/var/www
    networks:
      common:
        ipv4_address: 172.18.0.3

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: "user"
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    ports:
      - 3306:3306
    networks:
      common:
        ipv4_address: 172.18.0.5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    networks:
      common:
        ipv4_address: 172.18.0.6
    environment:
      PMA_ARBITRARY: 1

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/var:/var/lib/letsencrypt
      - ./www/certbot:/var/www/certbot
    networks:
      common:
        ipv4_address: 172.18.0.7

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

networks:
  common:
    ipam:
      config:
        - subnet: 172.18.0.0/24
